blank_issues_enabled: false
contact_links:
  - name: Svite GitHub Community
    url: https://github.com/svitejs/svite/discussions
    about: Please ask and answer questions here.
  - name: Svite Discord
    url: https://discord.gg/nzgMZJD
    about: If you want to chat, join our discord.
